In [47]:
import sqlite3
import csv
import pandas as pd

In [48]:
conn = sqlite3.connect('drug_deaths.db')
cursor = conn.cursor()

In [49]:
table_name = 'drug_deaths'

In [50]:
csv_file = 'drug_deaths_CT.csv'

In [51]:
create_table_query = '''
    CREATE TABLE drug_deaths (
        ID INTEGER PRIMARY KEY,
        Date VARCHAR,
        DataType INTEGER,
        Age INTEGER,
        Sex VARCHAR,
        Race VARCHAR,
        ResidenceCity VARCHAR,
        ResidenceCounty VARCHAR,
        ResidenceState VARCHAR,
        DeathCity VARCHAR,
        DeathCounty VARCHAR,
        Location VARCHAR,
        LocationifOther VARCHAR,
        DescriptionofInjury VARCHAR,
        InjuryPlace VARCHAR,
        InjuryCity VARCHAR,
        InjuryCounty VARCHAR,
        InjuryState VARCHAR,
        COD VARCHAR,
        OtherSignifican VARCHAR,
        Heroin INTEGER,
        Cocaine INTEGER,
        Fentanyl INTEGER,
        Fentanyl_Analogue INTEGER,
        Oxycodone INTEGER,
        Oxymorphone INTEGER,
        Ethanol INTEGER,
        Hydrocodone INTEGER,
        Benzodiazepine INTEGER,
        Methadone INTEGER,
        Amphet INTEGER,
        Tramad INTEGER,
        Morphine_NotHeroin INTEGER,
        Hydromorphone INTEGER,
        Other VARCHAR,
        OpiateNOS INTEGER,
        AnyOpioid INTEGER,
        MannerofDeath VARCHAR,
        DeathCityGeo VARCHAR,
        ResidenceCityGeo VARCHAR,
        InjuryCityGeo VARCHAR
        
    );
'''

In [52]:
# Execute the query to create the table
cursor.execute(create_table_query)

OperationalError: table drug_deaths already exists

In [53]:
# Commit the changes and close the connection
conn.commit()

In [54]:
print("Table 'drug_deaths' created successfully.")

Table 'drug_deaths' created successfully.

In [55]:
# Read the data from the 'drug_deaths' table into a pandas DataFrame
df = pd.read_sql_query("SELECT * FROM drug_deaths", conn)
# Close the connection
conn.close()

In [56]:
df

Empty DataFrame
Columns: [ID, Date, DataType, Age, Sex, Race, ResidenceCity, ResidenceCounty, ResidenceState, DeathCity, DeathCounty, Location, LocationifOther, DescriptionofInjury, InjuryPlace, InjuryCity, InjuryCounty, InjuryState, COD, OtherSignifican, Heroin, Cocaine, Fentanyl, Fentanyl_Analogue, Oxycodone, Oxymorphone, Ethanol, Hydrocodone, Benzodiazepine, Methadone, Amphet, Tramad, Morphine_NotHeroin, Hydromorphone, Other, OpiateNOS, AnyOpioid, MannerofDeath, DeathCityGeo, ResidenceCityGeo, InjuryCityGeo]
Index: []

[0 rows x 41 columns]

In [57]:
conn = sqlite3.connect('drug_deaths.db')
cursor = conn.cursor()

In [58]:
# Step 2: Create the 'drug_deaths' table if it doesn't exist
try:
    cursor.execute(create_table_query)
    print("Table 'drug_deaths' created successfully.")
except sqlite3.OperationalError:
    print("Table 'drug_deaths' already exists.")

Table 'drug_deaths' already exists.

In [63]:
# Step 4: Insert rows from the CSV file into the table
with open(csv_file, newline='') as csvfile:
    csv_reader = csv.reader(csvfile)
    next(csv_reader)  # Skip the header row
    for row in csv_reader:
        # Ensure that the row has the same number of values as the number of columns
        if len(row) == 40:
            cursor.execute('''
                INSERT INTO drug_deaths (Date, DataType, Age, Sex, Race, ResidenceCity, ResidenceCounty,
                                        ResidenceState, DeathCity, DeathCounty, Location, LocationifOther,
                                        DescriptionofInjury, InjuryPlace, InjuryCity, InjuryCounty,
                                        InjuryState, COD, OtherSignifican, Heroin, Cocaine, Fentanyl,
                                        Fentanyl_Analogue, Oxycodone, Oxymorphone, Ethanol, Hydrocodone,
                                        Benzodiazepine, Methadone, Amphet, Tramad, Morphine_NotHeroin,
                                        Hydromorphone, Other, OpiateNOS, AnyOpioid, MannerofDeath,
                                        DeathCityGeo, ResidenceCityGeo, InjuryCityGeo)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', row)
        else:
            print(f"Skipping row with incorrect number of values: {row}")

Skipping row with incorrect number of values: ['0', '14-0273', '6/28/2014 0:00', '1', '', '', '', '', '', '', '', '', '', '', 'substance', '', '', '', '', 'Acute fent, hydrocod, benzodiazepine', '', '0', '0', '1', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'CT\n(41.575155, -72.738288)', 'CT\n(41.575155, -72.738288)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['1', '13-0102', '3/21/2013 0:00', '0', '48', 'Male', 'Black', 'NORWALK', '', '', 'NORWALK', 'FAIRFIELD', 'Hospital', '', '', '', '', '', '', 'Cocaine Intoxication', '', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Norwalk, CT\n(41.11805, -73.412906)', 'NORWALK, CT\n(41.11805, -73.412906)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['2', '16-0165', '3/13/2016 0:00', '0', '30', 'Female', 'White', 'SANDY HOOK', 'FAIRFIELD', 'CT', 'DANBURY', '', 'Hospital', '', 'Substance Abuse', 'Unknown', 'UNKNOWN', '', '', 'Acute Heroin and Cocaine Intoxication', '', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'Danbury, CT\n(41.393666, -73.451539)', 'SANDY HOOK, CT\n(41.419998, -73.282501)', '']
Skipping row with incorrect number of values: ['3', '16-0208', '3/31/2016 0:00', '0', '23', 'Male', 'White', 'RYE', 'WESTCHESTER', 'NY', 'GREENWICH', '', 'Hospital', '', 'substance abuse', 'Residence', 'RYE', '', '', 'Acute Fentanyl and Morphine Intoxication', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'Greenwich, CT\n(41.026526, -73.628549)', '', '']
Skipping row with incorrect number of values: ['4', '13-0052', '2/13/2013 0:00', '0', '22', 'Male', 'Asian, Other', 'FLUSHING', 'QUEENS', '', 'GREENWICH', 'FAIRFIELD', 'Hospital', '', 'Transdermal Absorption', 'Other', '', '', '', 'Fentanyl Intoxication', '', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Greenwich, CT\n(41.026526, -73.628549)', '', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['5', '14-0277', '6/29/2014 0:00', '0', '23', 'Male', 'White', 'BRISTOL', '', '', 'BRISTOL', 'HARTFORD', 'Residence', '', 'Inhalation', 'Residence', '', '', '', 'Heroin Intoxication', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'BRISTOL, CT\n(41.673037, -72.945791)', 'BRISTOL, CT\n(41.673037, -72.945791)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['6', '12-0205', '8/12/2012 0:00', '0', '21', 'Female', 'White', 'WEST HARTFORD', 'HARTFORD', '', 'WEST HARTFORD', 'HARTFORD', 'Residence', '', 'Used Heroin', 'Residence', '', '', '', 'Heroin Toxicity', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'WEST HARTFORD, CT\n(41.762008, -72.741807)', 'WEST HARTFORD, CT\n(41.762008, -72.741807)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['7', '13-0404', '11/10/2013 0:00', '0', '40', 'Female', 'White', 'HAMDEN', 'NEW HAVEN', '', 'NEW HAVEN', 'NEW HAVEN', 'Hospital', '', '', '', '', '', '', 'Complications of Cocaine Intoxication', '', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'New Haven, CT\n(41.308252, -72.924161)', 'HAMDEN, CT\n(41.382918, -72.907743)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['8', '12-0107', '4/25/2012 0:00', '0', '40', 'Male', 'White', 'EAST HARTFORD', 'HARTFORD', '', 'EAST HARTFORD', 'HARTFORD', 'Residence', '', 'Used Heroin', 'Residence', '', '', '', 'Heroin Toxicity', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'EAST HARTFORD, CT\n(41.769319, -72.643785)', 'EAST HARTFORD, CT\n(41.769319, -72.643785)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['9', '13-0161', '5/15/2013 0:00', '0', '50', 'Male', 'White', 'MONTVILLE', 'NEW LONDON', '', 'MONTVILLE', 'NEW LONDON', 'Residence', '', 'Ingestion', 'Residence', '', '', '', 'Oxycodone Intoxication', '', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'MONTVILLE, CT\n(41.45303, -72.136336)', 'MONTVILLE, CT\n(41.45303, -72.136336)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['10', '12-0218', '8/23/2012 0:00', '0', '26', 'Female', 'Hispanic, White', '', '', '', 'STRATFORD', 'FAIRFIELD', 'Other', 'Honey Spot', 'Injection/Inhalation', 'Hotel or Motel', '', '', '', 'Multiple Drug Toxicity', '', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'STRATFORD, CT\n(41.200888, -73.131323)', 'CT\n(41.575155, -72.738288)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['11', '15-0334', '7/5/2015 0:00', '1', '49', 'Female', 'White', '', '', '', 'NEW HAVEN', 'NEW HAVEN', 'Hospital', '', '', 'Unknown', '', '', '', 'Acute intoxication from the combined effects of heroin and methadone', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '0', '1', 'Accident', 'New Haven, CT\n(41.308252, -72.924161)', 'CT\n(41.575155, -72.738288)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['12', '15-0728', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Unknown', '', '', '', 'Ruptured Aneurysm of right Iliac Artery with Hemoperitoneum', 'Acute Cocaine', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'CT\n(41.575155, -72.738288)', 'CT\n(41.575155, -72.738288)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['13', '15-0232', '5/14/2015 0:00', '1', '50', 'Male', 'White', 'DANBURY', 'FAIRFIELD', 'CT', 'DANBURY', 'FAIRFIELD', 'Residence', '', '', 'Residence', '', '', '', 'Heroin Intoxication', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'DANBURY, CT\n(41.393666, -73.451539)', 'DANBURY, CT\n(41.393666, -73.451539)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['14', '16-0028', '1/13/2016 0:00', '0', '29', 'Male', 'Black', 'NEW HAVEN', 'NEW HAVEN', 'CT', 'NEW HAVEN', '', 'Residence', '', 'Substance Abuse', 'Residence', 'NEW HAVEN', '', '', 'Acute Heroin Intoxication in a Person Taking Clonazepam, Amphetamine, Citalopram, and Aripiprazole', '', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '', '0', '1', 'Accident', 'NEW HAVEN, CT\n(41.308252, -72.924161)', 'NEW HAVEN, CT\n(41.308252, -72.924161)', 'NEW HAVEN, CT\n(41.308252, -72.924161)']
Skipping row with incorrect number of values: ['15', '13-0279', '8/19/2013 0:00', '0', '45', 'Male', 'White', 'HARTFORD', 'HARTFORD', '', 'HARTFORD', 'HARTFORD', 'Residence', '', 'Ingestion', 'Residence', '', '', '', 'Methadone Intoxication', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '0', '0', 'Accident', 'HARTFORD, CT\n(41.765775, -72.673356)', 'HARTFORD, CT\n(41.765775, -72.673356)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['16', '14-0042', '1/29/2014 0:00', '0', '29', 'Female', 'White', 'CANTERBURY', '', '', 'HARTFORD', '', 'Hospital', '', 'Substance Abuse', 'Unknown', '', '', '', 'Acute intoxication due to the combined effects of heroin, Citalopram and Clonazepam', '', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Hartford, CT\n(41.765775, -72.673356)', 'CANTERBURY, CT\n(41.698351, -71.971118)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['17', 'Dec-60', '3/2/2012 0:00', '0', '42', 'Male', 'White', 'WALLINGFORD', 'NEW HAVEN', '', 'WALLINGFORD', 'NEW HAVEN', 'Residence', '', 'Ingestion', 'Residence', '', '', '', 'Ethanol and Oxymorphone Toxicity', '', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'WALLINGFORD, CT\n(41.454408, -72.818414)', 'WALLINGFORD, CT\n(41.454408, -72.818414)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['18', '16-0065', '1/30/2016 0:00', '0', '54', 'Male', 'White', 'MIDDLETOWN', 'MIDDLESEX', 'CT', 'MIDDLETOWN', '', 'Residence', '', 'Substance Abuse Including Injection of Heroin', 'Residence', 'MIDDLETOWN', '', '', 'Acute Heroin Intoxication While Using Alcohol, Trazodone, Bupropion and Abilify', '', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'MIDDLETOWN, CT\n(41.544654, -72.651713)', 'MIDDLETOWN, CT\n(41.544654, -72.651713)', 'MIDDLETOWN, CT\n(41.544654, -72.651713)']
Skipping row with incorrect number of values: ['19', '16-0889', '12/20/2016 0:00', '0', '32', 'Male', 'White', 'WINDHAM', 'WINDHAM', 'CT', 'WINDHAM', '', 'Residence', '', '', '', 'WINDHAM', '', '', 'Acute Intoxication due to the Combined Effects of Fentanyl, Heroin, Clonazepam and Nordiazepam', '', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'Windham, CT\n(41.699744, -72.157703)', 'WINDHAM, CT\n(41.699744, -72.157703)', 'WINDHAM, CT\n(41.699744, -72.157703)']
Skipping row with incorrect number of values: ['20', '14-0474', '11/14/2014 0:00', '0', '47', 'Male', 'White', 'BRIDGEPORT', '', '', 'BRIDGEPORT', 'FAIRFIELD', 'Residence', '', 'substance abuse', 'Residence', '', '', '', 'Acute intoxication due to the combined effects of heroin and alcohol', '', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'BRIDGEPORT, CT\n(41.179195, -73.189476)', 'BRIDGEPORT, CT\n(41.179195, -73.189476)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['21', '15-0263', '6/2/2015 0:00', '1', '39', 'Female', 'White', 'ANSONIA', 'NEW HAVEN', 'CT', 'DERBY', 'NEW HAVEN', 'Hospital', '', '', 'Residence', 'ANSONIA', 'NEW HAVEN', 'CT', 'Intoxication due to the Combined Effects of Methadone and Diphenhydramine', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '0', '1', 'Accident', 'Derby, CT\n(41.322959, -73.089594)', 'ANSONIA, CT\n(41.34198, -73.078296)', 'ANSONIA, CT\n(41.34198, -73.078296)']
Skipping row with incorrect number of values: ['22', '14-0188', '5/2/2014 0:00', '0', '27', 'Male', '', 'HAMDEN', '', '', 'NEW HAVEN', 'NEW HAVEN', 'Hospital', '', 'Ingestion', 'Residence', '', '', '', 'Intoxication due to the combined effects of Oxycodone, Oxymorphone, Clonazepam, and Alprazolam', '', '0', '0', '0', '0', '1', '1', '0', '0', '1', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'New Haven, CT\n(41.308252, -72.924161)', 'HAMDEN, CT\n(41.382918, -72.907743)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['23', '16-0688', '10/7/2016 0:00', '0', '34', 'Male', 'White', 'COS COB', 'FAIRFIELD', 'CT', 'COS COB', '', 'Residence', '', 'Substance Abuse', 'Residence', 'COS COB', '', '', 'Acute Intoxication due to the Combined Effects of Fentanyl and Heroin', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'COS COB, CT\n(41.037899, -73.599776)', 'COS COB, CT\n(41.037899, -73.599776)', 'COS COB, CT\n(41.037899, -73.599776)']
Skipping row with incorrect number of values: ['24', '16-0495', '7/16/2016 0:00', '0', '27', 'Female', 'White', 'STRATFORD', 'FAIRFIELD', 'CT', 'STRATFORD', '', 'Residence', '', 'Substance Abuse', 'Residence', 'STRATFORD', '', '', 'Acute Intoxication due to the Combined Effects of Acetyl Fentanyl, Fentanyl, and Heroin', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'STRATFORD, CT\n(41.200888, -73.131323)', 'STRATFORD, CT\n(41.200888, -73.131323)', 'STRATFORD, CT\n(41.200888, -73.131323)']
Skipping row with incorrect number of values: ['25', '17-0817', '10/13/2017 0:00', '1', '25', 'Male', 'White', 'MERIDEN', 'NEW HAVEN', 'CT', 'MERIDEN', 'NEW HAVEN', 'Hospital', '', 'Substance abuse', 'Residence', 'MERIDEN', 'NEW HAVEN', 'CT', 'ACUTE COMBINED HEROIN, FENTANYL, ACETYL FENTANYL AND COCAINE TOXICITIES', '', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Meriden, CT\n(41.537589, -72.8011)', 'MERIDEN, CT\n(41.537589, -72.8011)', 'MERIDEN, CT\n(41.537589, -72.8011)']
Skipping row with incorrect number of values: ['26', '18-0095', '2/10/2018 0:00', '1', '51', 'Male', 'White', 'HARTFORD', 'HARTFORD', 'CT', 'HARTFORD', 'HARTFORD', 'Hospital', '', 'Drug Use', 'Other, Public Buildings', 'HARTFORD', 'HARTFORD', '', 'Acute IntoxicationCombined Effects of Ethanol, Alprazolam, Topiramate, Fluoxetine, and Fentanyl', '', '0', '0', '1', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'Hartford, CT\n(41.765775, -72.673356)', 'HARTFORD, CT\n(41.765775, -72.673356)', 'HARTFORD, CT\n(41.765775, -72.673356)']
Skipping row with incorrect number of values: ['27', '15-0182', '4/12/2015 0:00', '1', '23', 'Male', 'White', 'DANBURY', 'FAIRFIELD', 'CT', 'DANBURY', 'FAIRFIELD', 'Other', '', '', 'Other', '', '', '', 'Heroin and Ethanol Intoxication', '', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'DANBURY, CT\n(41.393666, -73.451539)', 'DANBURY, CT\n(41.393666, -73.451539)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['28', '15-0098', '2/27/2015 0:00', '1', '35', 'Male', 'White', 'NEW BRITAIN', 'HARTFORD', 'CT', 'HARTFORD', 'HARTFORD', 'Hospital', '', '', 'Restaurant', '', '', '', 'Acute Fentanyl Toxicity', '', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'Hartford, CT\n(41.765775, -72.673356)', 'NEW BRITAIN, CT\n(41.667528, -72.783437)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['29', '18-0285', '4/11/2018 0:00', '1', '25', 'Male', 'Hispanic, White', 'HARRISBURG', 'DAUPHIN', 'PA', 'NEW HAVEN', 'NEW HAVEN', 'Nursing Home', '', 'Substance Abuse', 'Unknown', '', '', '', 'Complications of Anoxic-Ischemic EncephalopathyAcute Opioid Intoxication', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '1', '1', 'Accident', 'NEW HAVEN, CT\n(41.308252, -72.924161)', 'HARRISBURG, CT\n(41.617199, -73.284203)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['30', '16-0316', '5/10/2016 0:00', '0', '43', 'Male', 'White', 'MELROSE', 'MIDDLESEX', 'MA', 'ENFIELD', '', 'Other', 'Motel 6', 'substance abuse', 'Hotel or Motel', 'ENFIELD', '', '', 'Acute Heroin, Fentanyl and Cocaine Toxicities Associated With Alprazolam and Alcohol Use', '', '1', '1', '1', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'ENFIELD, CT\n(41.976501, -72.591985)', 'MELROSE, CT\n(41.9375, -72.521698)', 'ENFIELD, CT\n(41.976501, -72.591985)']
Skipping row with incorrect number of values: ['31', '13-0441', '12/4/2013 0:00', '0', '48', 'Male', 'White', 'NORTH SALEM', 'WESTCHESTER', '', 'NORWALK', 'FAIRFIELD', 'Hospital', '', 'substance abuse', 'Unknown', '', '', '', 'Acute intoxication due to the combined effects of heroin, Alprazolam and ethanol', '', '1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Norwalk, CT\n(41.11805, -73.412906)', 'NORTH SALEM, CT\n(41.8978, -72.893097)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['32', '18-0468', '6/18/2018 0:00', '1', '40', 'Female', 'White', 'TORRINGTON', 'LITCHFIELD', 'CT', 'TORRINGTON', 'LITCHFIELD', 'Residence', '', 'Substance abuse', 'Residence', 'TORRINGTON', 'LITCHFIELD', '', 'ACUTE COMBINED FENTANYL, HEROIN AND ALCOHOL TOXICITY', 'RECENT COCAINE USE', '1', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'Torrington, CT\n(41.812186, -73.101552)', 'TORRINGTON, CT\n(41.812186, -73.101552)', 'TORRINGTON, CT\n(41.812186, -73.101552)']
Skipping row with incorrect number of values: ['33', '18-0355', '5/9/2018 0:00', '1', '49', 'Female', 'White', 'SOUTHBURY', 'NEW HAVEN', 'CT', 'WATERBURY', 'NEW HAVEN', 'Hospital', '', 'Drug abuse while traveling in vehicle', 'In Vehicle', '', '', '', 'Multidrug Toxicity Including Ethanol, Cocaine, and Sertraline', '', '0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Waterbury, CT\n(41.554261, -73.043069)', 'SOUTHBURY, CT\n(41.466592, -73.203497)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['34', '17-0907', '11/16/2017 0:00', '1', '40', 'Male', 'Black', 'NEW HAVEN', 'NEW HAVEN', 'CT', 'NEW HAVEN', 'NEW HAVEN', 'Hospital', '', 'Substance Abuse', 'Residence', 'NEW HAVEN', 'NEW HAVEN', 'CT', 'Acute Intoxication From the Combined Effects of Cocaine, Fentanyl, Heroin, and Alcohol', '', '1', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'New Haven, CT\n(41.308252, -72.924161)', 'NEW HAVEN, CT\n(41.308252, -72.924161)', 'NEW HAVEN, CT\n(41.308252, -72.924161)']
Skipping row with incorrect number of values: ['35', '15-0475', '9/14/2015 0:00', '1', '51', 'Male', 'White', 'MIDDLETOWN', 'MIDDLESEX', 'CT', 'MIDDLETOWN', 'MIDDLESEX', 'Residence', '', '', 'Residence', 'MIDDLETOWN', 'MIDDLESEX', 'CT', 'Acute Intoxication ethanol, hydrocodone, and benzodiazepines', '', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '0', '0', '', '0', '1', 'Accident', 'MIDDLETOWN, CT\n(41.544654, -72.651713)', 'MIDDLETOWN, CT\n(41.544654, -72.651713)', 'MIDDLETOWN, CT\n(41.544654, -72.651713)']
Skipping row with incorrect number of values: ['36', '14-0490', '11/22/2014 0:00', '0', '25', 'Male', 'White', 'DARIEN', '', '', 'NORWALK', 'FAIRFIELD', 'Hospital', '', 'Drug Use', 'Residence', '', '', '', 'Intoxication due to the combined effects of Ethanol and Heroin', '', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Norwalk, CT\n(41.11805, -73.412906)', 'DARIEN, CT\n(41.080002, -73.467371)', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['37', '15-0314', '6/28/2015 0:00', '1', '55', 'Female', 'White', 'SAUGUS', 'ESSEX', 'MA', 'MASHANTUCKET', 'NEW LONDON', 'Other', '', '', 'Unknown', '', '', '', 'ethanol, clonazepam', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'MASHANTUCKET, CT\n(41.471499, -71.956392)', '', 'CT\n(41.575155, -72.738288)']
Skipping row with incorrect number of values: ['38', '15-0687', '12/7/2015 0:00', '1', '56', 'Male', 'Black', 'WATERBURY', 'NEW HAVEN', 'CT', 'WATERBURY', 'NEW HAVEN', 'Hospital', '', '', 'Residence', 'WATERBURY', 'NEW HAVEN', 'CT', 'acute Cocaine, CV disease', '', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'accident', 'Waterbury, CT\n(41.554261, -73.043069)', 'WATERBURY, CT\n(41.554261, -73.043069)', 'WATERBURY, CT\n(41.554261, -73.043069)']
Skipping row with incorrect number of values: ['39', '17-0888', '11/11/2017 0:00', '1', '39', 'Male', 'White', 'MERIDEN', 'NEW HAVEN', 'CT', 'MERIDEN', 'NEW HAVEN', 'Other', 'Hotel/Motel', 'Substance abuse', 'Hotel or Motel', 'MERIDEN', 'NEW HAVEN', 'CT', 'Acute Intoxication due to the Combined Effects of Fluorobutyryl Fentanyl, Heroin, and Ethanol', '', '1', '0', '1', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '', '0', '0', 'Accident', 'Meriden, CT\n(41.537589, -72.8011)', 'MERIDEN, CT\n(41.537589, -72.8011)', 'MERIDEN, CT\n(41.537589, -72.8011)']

In [64]:
df

Empty DataFrame
Columns: [ID, Date, DataType, Age, Sex, Race, ResidenceCity, ResidenceCounty, ResidenceState, DeathCity, DeathCounty, Location, LocationifOther, DescriptionofInjury, InjuryPlace, InjuryCity, InjuryCounty, InjuryState, COD, OtherSignifican, Heroin, Cocaine, Fentanyl, Fentanyl_Analogue, Oxycodone, Oxymorphone, Ethanol, Hydrocodone, Benzodiazepine, Methadone, Amphet, Tramad, Morphine_NotHeroin, Hydromorphone, Other, OpiateNOS, AnyOpioid, MannerofDeath, DeathCityGeo, ResidenceCityGeo, InjuryCityGeo]
Index: []

[0 rows x 41 columns]

In [ ]:
# Commit the changes and close the connection
conn.commit()
conn.close()